//
//  NewsDetailsPresenter.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsPresentationLogic
{
  func presentSomething(response: NewsDetails.Something.Response)
}

class NewsDetailsPresenter: NewsDetailsPresentationLogic
{
  weak var viewController: NewsDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewsDetails.Something.Response)
  {
    let viewModel = NewsDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
