//
//  NewsDetailsInteractor.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsBusinessLogic
{
  func doSomething(request: NewsDetails.Something.Request)
}

protocol NewsDetailsDataStore
{
    var new: Article! { get set }
}

class NewsDetailsInteractor: NewsDetailsBusinessLogic, NewsDetailsDataStore
{
    var new: Article!
  var presenter: NewsDetailsPresentationLogic?
  var worker: NewsDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewsDetails.Something.Request)
  {
    worker = NewsDetailsWorker()
    worker?.doSomeWork()
    
    let response = NewsDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
