//
//  NewsDetailsRouter.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsDetailsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NewsDetailsDataPassing
{
    var dataStore: NewsDetailsDataStore? { get }
}

class NewsDetailsRouter: NSObject, NewsDetailsRoutingLogic, NewsDetailsDataPassing
{
    weak var viewController: NewsDetailsViewController?
    var dataStore: NewsDetailsDataStore?
}
