//
//  NewsDetailsInteractor.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsBusinessLogic
{
    func getNews()
}

protocol NewsDetailsDataStore
{
    var news: Article! { get set }
}

class NewsDetailsInteractor: NewsDetailsBusinessLogic, NewsDetailsDataStore
{
    var news: Article!
    var presenter: NewsDetailsPresentationLogic?
    var worker: NewsDetailsWorker?
    func getNews()
    {
        worker = NewsDetailsWorker()
        self.presenter?.presentNews(response: NewsDetails.FetchPost.Response(data: news))
    }
}
