//
//  FavoritesPresenter.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesPresentationLogic
{
    func presentFavoritedNews(response: FavoritedNews.FetchPost.Response)
    func presentFetchedManagedNews(response: FavoritedNews.FetchManagedPost.Response)
}

class FavoritesPresenter: FavoritesPresentationLogic
{
    weak var viewController: FavoritesDisplayLogic?
    
    func presentFavoritedNews(response: FavoritedNews.FetchPost.Response)
    {
        let viewModel = FavoritedNews.FetchPost.ViewModel(post: response.data)
        viewController?.displayUI(viewModel: viewModel)
    }
    
    func presentFetchedManagedNews(response: FavoritedNews.FetchManagedPost.Response) {
        let viewModel = FavoritedNews.FetchManagedPost.ViewModel(post: response.data)
        viewController?.displayFetchedManagedNews(viewModel: viewModel)
    }
}
