//
//  NewsListWorker.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class NewsListWorker
{
    func fetchNews(completionHandler: @escaping([Article]?, Error?) -> Void) {
        let urlString = UrlClass().getNewsUrl()
        DispatchQueue.main.async {
            AF.request(urlString, method: .get).validate().responseData { (response) in
                switch response.result {
                case .success(let value):
                    do {
                        let responseModel = try JSONDecoder().decode(NewsModel.self, from: value)
                        guard responseModel.status == "ok" else {return}
                        completionHandler(responseModel.articles, nil)
                    } catch let err {
                        print(String(describing: err))
                    }
                case .failure(let err):
                    completionHandler(nil, err)
                }
            }
        }
    }
}
