//
//  NewsListInteractor.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListBusinessLogic
{
    func fetchNews(request: News.FetchPost.Request)
}

protocol NewsListDataStore
{
    var new: [Article]? { get }
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore
{
    internal var new: [Article]?
    var presenter: NewsListPresentationLogic?
    var worker: NewsListWorker?
  
    func fetchNews(request: News.FetchPost.Request)
  {
    worker = NewsListWorker()
      worker?.fetchNews(completionHandler: { [weak self] (data, error) in
          self?.new = data
          let response = News.FetchPost.Response(errorMessage: error?.localizedDescription, data: data)
          self?.presenter?.presentFetchedNews(response: response)
      })
  }
}
