//
//  NewsListInteractor.swift
//  VIPNewsApp
//
//  Created by admin on 7.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListBusinessLogic
{
  func doSomething(request: NewsList.Something.Request)
}

protocol NewsListDataStore
{
  //var name: String { get set }
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore
{
  var presenter: NewsListPresentationLogic?
  var worker: NewsListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewsList.Something.Request)
  {
    worker = NewsListWorker()
//    worker?.doSomeWork()
    
    let response = NewsList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
